# Generated by Django 5.1.4 on 2026-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.CharField(max_length=300)),
                ("business_problem", models.TextField()),
                ("tools_used", models.CharField(max_length=300)),
                (
                    "key_features",
                    models.TextField(help_text="One bullet per line, prefix with - "),
                ),
                ("role_contribution", models.TextField()),
                ("biggest_challenge", models.TextField()),
                ("what_learned", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "AI / Agent"),
                            ("ml", "Machine Learning"),
                            ("media", "Media / Generative"),
                            ("workflow", "Workflow / Automation"),
                            ("web", "Web App"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
