services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings.prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SEED_FIXTURES
        value: "1"
