# Generated by Django 5.1.4 on 2026-05-05 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lang", "Programming Languages"),
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("testing", "Testing"),
                            ("db", "Databases"),
                            ("cloud", "Cloud"),
                            ("tools", "Tools / Integrations"),
                            ("practices", "Engineering Practices"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "name"],
                "unique_together": {("name", "category")},
            },
        ),
    ]
